// SingleProd element contains the single product data, plus edit and remove buttons.
// it is generated by ShowProdList.js component by mapping the array of products received by GetAllProducts.js
// and returning a single element for any product in the arrays.
// its method only returns the product id to the parent (getAllProd) which contains
// axios methods for CRUD on Express server 

console.log('...opening')

import React, {  Component } from 'react';
import Popup from "reactjs-popup";
const deleteDataRoute = 'http://localhost:3000/products/deletedata/'; //server side address
const updateDataRoute = 'http://localhost:3000/products/updatedata/'; //server side address
// TODO: this links should not be hardcoded

class SingleProd extends Component {

    constructor(props) {

        
    super(props);

    this.execCRUDAction = this.execCRUDAction.bind(this)
        
    this.state = {
      compName: 'SingleProd.js',
      errorToHandle: false,
      product: []
    };
  }

  componentDidMount() {
    console.log(this.state.compName, ' mounted');
    //copy the single product data in the component state
    this.setState({
      product: this.props.product
    });
    console.log(this.state);
  };

  componentWillUnmount() {
    console.log(this.state.compName, ' unmounted');
  };

  execCRUDAction(actionArgs) {
      this.props.handleCRUDType(
          {_id: this.props.product._id,
           crudAction: actionArgs.target.value
          }
      )
  };

  //On buttonclick the product Id is sent to parent
  sendProductIdToParent = (crudAction) => {
    this.props.updateProdsList(this.props.product._id);
    console.log('sendProductIdToParent triggered');
  };

  // getButtonValue = value => () => {
  //     console.log(value);
  // };
     
  render() {
    console.log('SingleProd this:', this);
    const testValue = 'testValue';
    return (
      <div>
        <hr/>
        <hr/>
        <h6> rendered {this.state.compName} </h6>
        <h6> -------- </h6>
         {/* PRODUCT INFO */} 
          <h6>id: {this.props.product._id}</h6>
          <h6>artist: {this.props.product.artist}</h6>
          <h6>title: {this.props.product.title}</h6>
          <h6>year: {this.props.product.year}</h6>
     
        {/* REMOVE BUTTON */} 
        <button
          onClick={(e) => {
              e.preventDefault();
              this.execCRUDAction(e);
              /* this.sendProductIdToParent(e.target.value); */
              /* this.props.handleCRUDType(e.target.value); */

          }}
          value='CRUD_delete' //e.target.value
          
          /* onClick={this.sendProductIdToParent} */
          /* value='CRUD_delete' */
        >
          Remove
        </button>
      </div>
    );
  };
};

export default SingleProd;


